Repository MicrosoftDocs/azure-docs.fr-fr, pull requests merged in 2019-01, with the labels that each got.

#202 Translation translation omission
  articles/data-factory/concepts-pipelines-activities.md
Labels: Accepted, Linguistic Suggestion, Source Issue

#209 Translation translation omission
  articles/azure-functions/functions-host-json.md
Labels: Accepted, Technical Issue

#208 Translation translation omission
  articles/azure-functions/functions-host-json-v1.md
Labels: Accepted, Technical Issue

#207 Translation translation omission
  articles/azure-functions/functions-bindings-cosmosdb.md
Labels: Accepted, Technical Issue

#206 Translation translation omission
  articles/data-factory/tutorial-copy-data-tool.md
Labels: Accepted, Technical Issue

#205 Translation translation omission
  articles/data-factory/concepts-pipeline-execution-triggers.md
Labels: Accepted, Technical Issue

#204 Translation translation omission
  articles/azure-functions/functions-bindings-cosmosdb-v2.md
Labels: Accepted, Technical Issue

#203 Translation translation omission
  articles/data-factory/v1/data-factory-create-pipelines.md
Labels: Accepted, Technical Issue

#212 Translation translation omission
  articles/data-factory/connector-amazon-redshift.md
Labels: Accepted, Technical Issue

#211 Translation translation omission
  articles/data-factory/concepts-datasets-linked-services.md
Labels: Accepted, Technical Issue

#215 Translation translation omission
  articles/data-factory/connector-azure-blob-storage.md
Labels: Accepted, Technical Issue

#216 Translation translation omission
  articles/data-factory/connector-azure-cosmos-db.md
Labels: Accepted, Technical Issue

#217 Translation translation omission
  articles/data-factory/connector-azure-data-lake-store.md
Labels: Accepted, Technical Issue

#218 Translation translation omission
  articles/data-factory/connector-azure-search.md
Labels: Accepted, Technical Issue

#219 Translation translation omission
  articles/data-factory/connector-azure-sql-database.md
Labels: Accepted, Technical Issue

#220 Translation translation omission
  articles/data-factory/quickstart-create-data-factory-copy-data-tool.md
Labels: Accepted, Technical Issue

#221 Translation translation omission
  articles/data-factory/quickstart-create-data-factory-portal.md
Labels: Accepted, Technical Issue

#228 Translation translation omission
  articles/media-services/previous/media-services-overview.md
Labels: Accepted, Technical Issue

#227 Translation translation omission
  articles/media-services/previous/media-services-media-encoder-standard-formats.md
Labels: Accepted, Technical Issue

#223 Translation translation omission
  articles/data-factory/copy-activity-performance.md
Labels: Accepted, Technical Issue

#224 Translation translation omission
  articles/data-factory/copy-activity-overview.md
Labels: Accepted, Technical Issue

#225 Translation translation omission
  articles/data-factory/control-flow-expression-language-functions.md
Labels: Accepted, Technical Issue

#226 Translation translation omission
  articles/data-factory/introduction.md
Labels: Accepted, Technical Issue

#229 Translation translation omission
  articles/data-factory/v1/data-factory-sftp-connector.md
Labels: Accepted, Technical Issue

#231 Translation translation omission
  articles/data-factory/v1/data-factory-use-custom-activities.md
Labels: Accepted, Technical Issue

#244 Translation translation omission
  articles/data-factory/v1/data-factory-onprem-teradata-connector.md
Labels: Accepted, Technical Issue

#243 Translation translation omission
  articles/data-factory/v1/data-factory-onprem-sybase-connector.md
Labels: Accepted, Technical Issue

#242 Translation translation omission
  articles/data-factory/v1/data-factory-onprem-postgresql-connector.md
Labels: Accepted, Technical Issue

#239 Translation translation omission
  articles/data-factory/v1/data-factory-onprem-file-system-connector.md
Labels: Accepted, Technical Issue

#238 Translation translation omission
  articles/data-factory/v1/data-factory-onprem-db2-connector.md
Labels: Accepted, Technical Issue

#237 Translation translation omission
  articles/data-factory/v1/data-factory-onprem-cassandra-connector.md
Labels: Accepted, Technical Issue

#236 Translation translation omission
  articles/data-factory/v1/data-factory-on-premises-mongodb-connector.md
Labels: Accepted, Technical Issue

#248 Translation translation omission
  articles/data-factory/transform-data-using-hadoop-map-reduce.md
Labels: Accepted, Technical Issue

#247 Translation translation omission
  articles/data-factory/transform-data-using-hadoop-hive.md
Labels: Accepted, Technical Issue

#246 Translation translation omission
  articles/data-factory/transform-data-using-dotnet-custom-activity.md
Labels: Accepted, Technical Issue

#245 Translation translation omission
  articles/data-factory/transform-data-using-data-lake-analytics.md
Labels: Accepted, Technical Issue

#260 Translation translation omission
  articles/data-factory/connector-ftp.md
Labels: Accepted, Technical Issue

#259 Translation translation omission
  articles/data-factory/connector-file-system.md
Labels: Accepted, Technical Issue

#257 Translation translation omission
  articles/data-factory/connector-cassandra.md
Labels: Accepted, Technical Issue

#256 Translation translation omission
  articles/data-factory/connector-azure-table-storage.md
Labels: Accepted, Technical Issue

#265 Update private-dns-overview.md
  articles/dns/private-dns-overview.md
Labels: Accepted, Linguistic Suggestion

#277 Fix missing
  articles/azure-functions/functions-reference-python.md
Labels: Accepted, Linguistic Suggestion

#278 Fix missing
  articles/azure-maps/consumption-model.md
Labels: Accepted, Linguistic Suggestion

#279 Fix missing
  articles/azure-monitor/log-query/examples.md
Labels: In Progress, Linguistic Suggestion

#285 Fix missing
  articles/logic-apps/logic-apps-create-variables-store-values.md
Labels: Accepted, Linguistic Suggestion

#286 Fix missing
  articles/azure-resource-manager/move-support-resources.md
Labels: Accepted, Linguistic Suggestion

#280 Fix missing
  articles/cognitive-services/LUIS/luis-container-configuration.md
Labels: In Progress, Linguistic Suggestion
