Repository MicrosoftDocs/azure-docs.fr-fr, pull requests merged in 2019-10, with the labels that each got.

#628 changing visage by Face
  articles/cognitive-services/Face/index.yml
Labels: Accepted, Linguistic Suggestion

#631 changing Reconnaissance de l’orateur to Speaker recognition
  articles/cognitive-services/Speaker-recognition/Home.md
Labels: Accepted, Linguistic Suggestion

#630 Changing analyse de texte to Text analytics
  articles/cognitive-services/text-analytics/overview.md
Labels: Linguistic Suggestion, Partially Accepted

#629 changing 'visage' to Face
  articles/cognitive-services/Face/QuickStarts/csharp-sdk.md
Labels: Linguistic Suggestion, Partially Accepted

#637 Update index-policy.md
  articles/cosmos-db/index-policy.md
Labels: Accepted, Linguistic Suggestion

#638 Update index-policy.md
  articles/cosmos-db/index-policy.md
Labels: Accepted, Linguistic Suggestion

#643 Replace D'Azure CLI to Azure CLI
  articles/governance/policy/samples/keyvault-no-vnet-rules.md
Labels: In Progress

#649 Update backup-azure-vms-encryption.md
  articles/backup/backup-azure-vms-encryption.md
Labels: Accepted

#648 Update service-fabric-get-started-tomcat.md
  articles/service-fabric/service-fabric-get-started-tomcat.md
Labels: Accepted, Linguistic Suggestion

#647 Update specify-recognition-model.md
  articles/cognitive-services/Face/Face-API-How-to-Topics/specify-recognition-model.md
Labels: Accepted

#646 Update troubleshoot-app-service-redirection-app-service-url.md
  articles/application-gateway/troubleshoot-app-service-redirection-app-service-url.md
Labels: Accepted

#645 Language mistakes
  articles/aks/security-hardened-vm-host-image.md
Labels: Linguistic Suggestion, Partially Accepted
