Repository MicrosoftDocs/azure-docs.fr-fr, pull requests merged in 2019-06, with the labels that each got.

#414 Fix mistranslation
  articles/data-factory/v1/data-factory-pig-activity.md
Labels: Accepted

#411 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-postgresql-connector.md
Labels: Accepted

#412 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-sybase-connector.md
Labels: Accepted

#413 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-teradata-connector.md
Labels: Accepted

#415 Fix mistranslation
  articles/data-factory/v1/data-factory-salesforce-connector.md
Labels: Accepted, Linguistic Suggestion

#416 Fix mistranslation
  articles/data-factory/v1/data-factory-sftp-connector.md
Labels: Accepted, Linguistic Suggestion

#417 Fix mistranslation
  articles/active-directory/develop/active-directory-claims-mapping.md
Labels: Accepted, Linguistic Suggestion

#420 Fix mistranslation
  articles/data-factory/v1/data-factory-stored-proc-activity.md
Labels: Accepted, Linguistic Suggestion

#419 Fix mistranslation
  articles/data-factory/v1/data-factory-sqlserver-connector.md
Labels: Accepted, Linguistic Suggestion

#418 Fix mistranslation
  articles/data-factory/v1/data-factory-spark.md
Labels: Accepted, Linguistic Suggestion

#421 Fix comparison table
  articles/storage/common/storage-decide-blobs-files-disks.md
Labels: Accepted, Linguistic Suggestion

#422 Fix mistranslation
  articles/digital-twins/how-to-egress-endpoints.md
Labels: Accepted, Linguistic Suggestion

#425 Fix mistranslation
  articles/event-grid/event-schema-container-registry.md
Labels: Accepted, Linguistic Suggestion

#424 Fix mistranslation
  articles/event-grid/event-schema-blob-storage.md
Labels: Accepted, Linguistic Suggestion

#423 Fix mistranslation
  articles/event-grid/event-schema-azure-maps.md
Labels: Accepted, Linguistic Suggestion

#429 Fix mistranslation
  articles/event-grid/event-schema-service-bus.md
Labels: In Progress

#428 Fix mistranslation
  articles/event-grid/event-schema-resource-groups.md
Labels: In Progress

#427 Fix mistranslation
  articles/event-grid/event-schema-iot-hub.md
Labels: In Progress

#426 Fix mistranslation
  articles/event-grid/event-schema-event-hubs.md
Labels: In Progress

#432 Fix mistranslation
  articles/hdinsight/hdinsight-for-vscode.md
Labels: In Progress

#431 Fix mistranslation
  articles/event-grid/event-schema.md
Labels: In Progress

#430 Fix mistranslation
  articles/event-grid/event-schema-subscriptions.md
Labels: In Progress

#433 Fix mistranslation
  articles/load-balancer/create-load-balancer-rest-api.md
Labels: In Progress

#434 Fix mistranslation
  articles/logic-apps/logic-apps-exception-handling.md
Labels: In Progress

#435 Fix mistranslation
  articles/logic-apps/logic-apps-handle-large-messages.md
Labels: In Progress

#436 Fix mistranslation
  articles/logic-apps/logic-apps-track-integration-account-as2-tracking-schemas.md
Labels: In Progress

#437 Fix mistranslation
  articles/logic-apps/logic-apps-track-integration-account-custom-tracking-schema.md
Labels: In Progress

#438 Fix mistranslation
  articles/logic-apps/logic-apps-track-integration-account-x12-tracking-schema.md
Labels: In Progress

#439 Fix mistranslation
  articles/managed-applications/create-uidefinition-elements.md
Labels: In Progress

#440 Fix mistranslation
  articles/media-services/previous/media-services-motion-detection.md
Labels: In Progress

#441 Fix mistranslation
  articles/service-fabric/service-fabric-sfctl-application.md
Labels: In Progress

#442 Fix mistranslation
  articles/virtual-machine-scale-sets/virtual-machine-scale-sets-health-extension.md
Labels: In Progress

#447 Fix mistranslation
  articles/virtual-machines/extensions/azure-disk-enc-linux.md
Labels: In Progress

#446 Fix mistranslation
  articles/virtual-machines/extensions/agent-dependency-windows.md
Labels: In Progress

#445 Fix mistranslation
  articles/service-fabric/service-fabric-cluster-nodetypes.md
Labels: In Progress

#450 Fix mistranslation
  articles/virtual-machines/extensions/custom-script-linux.md
Labels: In Progress

#451 Fix mistranslation
  articles/virtual-machines/extensions/custom-script-linuxOstc.md
Labels: Accepted

#455 Fix mistranslation
  articles/virtual-machines/extensions/hpccompute-gpu-linux.md
Labels: Accepted, Linguistic Suggestion

#453 Fix mistranslation
  articles/virtual-machines/extensions/dsc-template.md
Labels: Accepted, Linguistic Suggestion

#454 Fix mistranslation
  articles/virtual-machines/extensions/dsc-windows.md
Labels: Accepted, Linguistic Suggestion

#452 Fix mistranslation
  articles/virtual-machines/extensions/custom-script-windows.md
Labels: Accepted, Linguistic Suggestion

#457 Fix mistranslation
  articles/virtual-machines/extensions/network-watcher-linux.md
Labels: In Progress

#456 Fix mistranslation
  articles/virtual-machines/extensions/hpccompute-gpu-windows.md
Labels: In Progress

#460 Fix mistranslation
  includes/data-factory-structure-for-rectangualr-datasets.md
Labels: In Progress

#458 Fix mistranslation
  articles/virtual-machines/extensions/network-watcher-windows.md
Labels: In Progress

#459 Fix mistranslation
  articles/virtual-machines/extensions/oms-linux.md
Labels: In Progress

#463 Fix mistranslation
  articles/azure-resource-manager/resource-group-template-functions-array.md
Labels: In Progress

#462 Fix mistranslation
  articles/analysis-services/analysis-services-async-refresh.md
Labels: In Progress

#461 Fix mistranslation
  articles/data-factory/v1/data-factory-build-your-first-pipeline-using-editor.md
Labels: In Progress

#468 Fix mistranslation
  articles/governance/blueprints/reference/blueprint-functions.md
Labels: In Progress

#465 Fix mistranslation
  articles/azure-resource-manager/resource-group-template-functions-deployment.md
Labels: In Progress

#466 Fix mistranslation
  articles/data-factory/concepts-pipelines-activities.md
Labels: In Progress

#467 Fix mistranslation
  articles/data-factory/control-flow-if-condition-activity.md
Labels: In Progress

#470 Fix mistranslation
  articles/logic-apps/logic-apps-workflow-actions-triggers.md
Labels: Accepted

#471 Fix mistranslation
  articles/logic-apps/logic-apps-workflow-definition-language.md
Labels: Accepted, Linguistic Suggestion

#472 Fix mistranslation
  articles/logic-apps/workflow-definition-language-functions-reference.md
Labels: Accepted

#473 Fix mistranslation
  articles/media-services/latest/media-services-event-schemas.md
Labels: Accepted, Linguistic Suggestion

#474 Fix mistranslation
  articles/active-directory/conditional-access/technical-reference.md
Labels: Accepted

#475 Fix mistranslation
  articles/automation/automation-graphical-authoring-intro.md
Labels: Accepted, Linguistic Suggestion

#478 Fix mistranslation
  articles/azure-monitor/insights/solutions-resources-searches-alerts.md
Labels: Accepted, Linguistic Suggestion

#477 Fix mistranslation
  articles/azure-cache-for-redis/cache-howto-manage-redis-cache-powershell.md
Labels: Accepted, Linguistic Suggestion

#479 Fix mistranslation
  articles/azure-monitor/insights/solutions-solution-file.md
Labels: Accepted, Linguistic Suggestion

#443 Fix translation
  articles/event-hubs/event-hubs-features.md
Labels: Accepted, Linguistic Suggestion

#480 Fix mistranslation
  articles/azure-monitor/log-query/unify-app-resource-data.md
Labels: Accepted

#481 Fix mistranslation
  articles/azure-monitor/platform/activity-log-export.md
Labels: Accepted

#482 Fix mistranslation
  articles/azure-monitor/platform/alerts-webhooks.md
Labels: Accepted

#483 Fix mistranslation
  articles/azure-monitor/platform/autoscale-understanding-settings.md
Labels: Accepted
