Repository MicrosoftDocs/azure-docs.fr-fr, pull requests merged in 2019-04, with the labels that each got.

#306 Update security-overview.md
  articles/virtual-network/security-overview.md
Labels: Accepted, Technical Issue

#312 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-sql-data-warehouse-connector.md
Labels: Accepted, In Progress

#311 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-table-connector.md
Labels: Accepted, In Progress

#310 Fix mistranslation
  articles/data-factory/connector-azure-sql-data-warehouse.md
Labels: Accepted, In Progress

#313 Fix mistranslation
  articles/azure-monitor/platform/api-alerts.md
Labels: Accepted, In Progress

#317 Fix mistranslation
  articles/data-factory/connector-azure-search.md
Labels: Accepted, In Progress, Linguistic Suggestion

#316 Fix mistranslation
  articles/azure-monitor/platform/archive-diagnostic-logs.md
Labels: Accepted, In Progress, Linguistic Suggestion

#315 Fix mistranslation
  articles/data-factory/connector-sql-server.md
Labels: Accepted, In Progress, Linguistic Suggestion

#314 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-sql-connector.md
Labels: Accepted, In Progress, Linguistic Suggestion

#318 Fix mistranslation
  articles/azure-monitor/insights/wire-data.md
Labels: Accepted, In Progress, Linguistic Suggestion

#319 Fix mistranslation
  articles/azure-monitor/platform/activity-logs-overview.md
Labels: Accepted, In Progress, Linguistic Suggestion

#320 Fix mistranslation
  articles/data-factory/connector-azure-sql-database-managed-insance.md
Labels: Accepted, In Progress, Linguistic Suggestion

#321 Fix mistranslation
  articles/data-factory/connector-azure-sql-database.md
Labels: Accepted, In Progress, Linguistic Suggestion

#323 Fix mistranslation
  articles/connectors/connectors-create-api-bingsearch.md
Labels: Accepted, In Progress

#322 Fix mistranslation
  articles/azure-monitor/insights/solutions-resources-automation.md
Labels: Accepted, In Progress

#325 Fix mistranslation
  articles/azure-maps/geofence-geojson.md
Labels: Accepted, In Progress

#324 Fix mistranslation
  articles/api-management/api-management-product-templates.md
Labels: Accepted, In Progress

#329 Fix mistranslation
  articles/automation/automation-manage-send-joblogs-log-analytics.md
Labels: Accepted, In Progress

#328 Fix mistranslation
  articles/automation/automation-solution-vm-management.md
Labels: Accepted, In Progress

#327 Fix mistranslation
  articles/azure-functions/functions-host-json.md
Labels: Accepted, In Progress

#326 Fix mistranslation
  articles/azure-functions/functions-host-json-v1.md
Labels: Accepted, In Progress

#332 Fix mistranslation
  articles/api-management/api-management-howto-use-azure-monitor.md
Labels: Accepted, In Progress

#330 Fix mistranslation
  articles/data-factory/control-flow-filter-activity.md
Labels: Accepted, In Progress

#331 Fix mistranslation
  articles/automation/automation-dsc-diagnostics.md
Labels: Accepted, In Progress

#337 Fix mistranslation
  articles/data-factory/connector-azure-table-storage.md
Labels: Accepted, In Progress

#336 Fix mistranslation
  articles/azure-monitor/insights/vminsights-log-search.md
Labels: Accepted, In Progress

#335 Fix mistranslation
  articles/data-factory/connector-web-table.md
Labels: Accepted, In Progress

#334 Fix mistranslation
  articles/api-management/api-management-howto-properties.md
Labels: Accepted, In Progress

#333 Fix mistranslation
  articles/api-management/api-management-error-handling-policies.md
Labels: Accepted, In Progress

#339 Fix mistranslation
  articles/azure-functions/functions-bindings-cosmosdb-v2.md
Labels: Accepted, In Progress

#338 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-search-connector.md
Labels: Accepted, In Progress
