Repository MicrosoftDocs/azure-docs.fr-fr, pull requests merged in 2019-07, with the labels that each got.

#484 Fix mistranslation
  articles/azure-monitor/platform/autoscale-webhook-email.md
Labels: Accepted

#486 Fix mistranslation
  articles/azure-monitor/platform/powershell-quickstart-samples.md
Labels: Accepted

#489 Fix mistranslation
  articles/blockchain/service/send-transaction.md
Labels: Accepted

#488 Fix mistranslation
  articles/blockchain/service/manage-consortium-powershell.md
Labels: Accepted

#490 Fix mistranslation
  articles/blockchain/workbench/configuration.md
Labels: Accepted

#491 Fix mistranslation
  articles/cognitive-services/Speech/API-Reference-REST/websocketprotocol.md
Labels: Accepted, Linguistic Suggestion

#493 Fix mistranslation
  articles/data-factory/v1/data-factory-create-datasets.md
Labels: Accepted, Linguistic Suggestion

#492 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-table-connector.md
Labels: Accepted, Linguistic Suggestion

#498 Fix mistranslation
  articles/data-factory/v1/data-factory-spark.md
Labels: Accepted

#496 Fix mistranslation
  articles/data-factory/v1/data-factory-http-connector.md
Labels: Accepted

#500 Fix mistranslation
  articles/data-factory/v1/data-factory-stored-proc-activity.md
Labels: Accepted

#499 Fix mistranslation
  articles/data-factory/v1/data-factory-sqlserver-connector.md
Labels: Accepted

#501 Fix mistranslation
  articles/hdinsight/domain-joined/apache-domain-joined-create-configure-enterprise-security-cluster.md
Labels: Accepted

#497 Fix typo
  articles/data-factory/v1/data-factory-pig-activity.md
Labels: Accepted

#495 Fix typo
  articles/data-factory/v1/data-factory-hive-activity.md
Labels: Accepted

#503 Fix mistranslation
  articles/hdinsight/hdinsight-hadoop-customize-cluster-linux.md
Labels: Accepted

#502 Fix mistranslation
  articles/hdinsight/hdinsight-hadoop-create-linux-clusters-adf.md
Labels: Accepted

#505 Fix mistranslation
  articles/mariadb/howto-restore-server-cli.md
Labels: Accepted, Linguistic Suggestion

#504 Fix mistranslation
  articles/managed-applications/create-uidefinition-elements.md
Labels: Accepted, Linguistic Suggestion

#506 Fix mistranslation
  articles/mariadb/tutorial-design-database-cli.md
Labels: Accepted, Linguistic Suggestion

#507 Fix mistranslation
  articles/mysql/howto-restore-server-cli.md
Labels: Accepted, Linguistic Suggestion

#509 Fix mistranslation
  articles/postgresql/howto-restore-server-cli.md
Labels: Accepted, Linguistic Suggestion

#508 Fix mistranslation
  articles/mysql/tutorial-design-database-using-cli.md
Labels: Accepted, Linguistic Suggestion

#510 Fix mistranslation
  articles/postgresql/tutorial-design-database-using-azure-cli.md
Labels: Accepted, Linguistic Suggestion

#512 Fix mistranslation
  articles/traffic-manager/traffic-manager-powershell-arm.md
Labels: Accepted

#513 Fix mistranslation
  articles/app-service-mobile/app-service-mobile-ios-get-started-offline-data.md
Labels: Accepted

#515 Fix mistranslation
  articles/azure-functions/functions-bindings-sendgrid.md
Labels: Accepted, Linguistic Suggestion

#514 Fix mistranslation
  articles/azure-cache-for-redis/cache-howto-manage-redis-cache-powershell.md
Labels: Accepted, Linguistic Suggestion

#519 Fix mistranslation
  articles/service-bus-messaging/service-bus-amqp-protocol-guide.md
Labels: Accepted

#520 Fix mistranslation
  articles/storage/common/storage-powershell-independent-clouds.md
Labels: Accepted, Linguistic Suggestion

#521 Fix mistranslation
  articles/azure-functions/functions-host-json-v1.md
Labels: Accepted, Linguistic Suggestion

#518 translation mistake
  articles/cognitive-services/Face/concepts/face-recognition.md
Labels: Accepted, Linguistic Suggestion

#524 Fix mistranslation
  articles/azure-functions/functions-reference-node.md
Labels: Accepted

#523 Fix mistranslation
  articles/azure-functions/functions-host-json.md
Labels: Accepted

#525 Fix mistranslation
  articles/azure-monitor/insights/solutions-resources-automation.md
Labels: Accepted

#516 correction of translation
  articles/cognitive-services/Face/concepts/face-detection.md
Labels: Accepted, Linguistic Suggestion

#517 fix translation mistakes
  articles/cognitive-services/Face/concepts/face-recognition.md
Labels: Accepted, Linguistic Suggestion, Source Issue

#527 Fix mistranslation
  articles/azure-monitor/platform/autoscale-understanding-settings.md
Labels: Accepted

#526 Fix mistranslation
  articles/azure-monitor/insights/solutions-resources-searches-alerts.md
Labels: Accepted

#529 Fix mistranslation
  articles/azure-resource-manager/resource-group-authoring-templates.md
Labels: Accepted, Linguistic Suggestion

#531 Fix mistranslation
  articles/azure-resource-manager/resource-group-template-functions-string.md
Labels: Accepted

#530 Fix mistranslation
  articles/azure-resource-manager/resource-group-template-functions-array.md
Labels: Accepted

#532 Fix mistranslation
  articles/blockchain/workbench/configuration.md
Labels: Accepted

#533 Fix mistranslation
  articles/blockchain/workbench/messages-overview.md
Labels: Accepted

#534 Fix mistranslation
  articles/cognitive-services/Speech/API-Reference-REST/websocketprotocol.md
Labels: Accepted

#535 Fix mistranslation
  articles/connectors/connectors-create-api-bingsearch.md
Labels: Accepted

#536 Fix mistranslation
  articles/data-factory/concepts-pipelines-activities.md
Labels: Accepted

#537 Fix mistranslation
  articles/data-factory/connector-amazon-marketplace-web-service.md
Labels: Accepted

#539 Fix mistranslation
  articles/data-factory/connector-amazon-redshift.md
Labels: Accepted, Linguistic Suggestion

#540 Fix mistranslation
  articles/data-factory/connector-amazon-simple-storage-service.md
Labels: Accepted

#541 Fix mistranslation
  articles/data-factory/connector-azure-blob-storage.md
Labels: Accepted

#542 Fix mistranslation
  articles/data-factory/connector-azure-data-lake-storage.md
Labels: Accepted, Linguistic Suggestion

#543 Fix mistranslation
  articles/data-factory/connector-azure-data-lake-store.md
Labels: Accepted

#544 Update billing-download-azure-invoice-daily-usage-date.md
  articles/billing/billing-download-azure-invoice-daily-usage-date.md
Labels: Accepted, Linguistic Suggestion

#545 Fix mistranslation
  articles/data-factory/connector-azure-file-storage.md
Labels: Accepted
