Repository MicrosoftDocs/azure-docs.fr-fr, pull requests merged in 2019-05, with the labels that each got.

#342 Fix mistranslation
  articles/data-factory/connector-amazon-redshift.md
Labels: Accepted, In Progress

#345 Fix mistranslation
  articles/data-factory/connector-azure-cosmos-db-mongodb-api.md
Labels: Accepted, In Progress

#344 Fix mistranslation
  articles/data-factory/connector-azure-blob-storage.md
Labels: Accepted, In Progress

#348 Fix mistranslation
  articles/data-factory/connector-azure-data-lake-storage.md
Labels: Accepted, In Progress

#343 Fix mistranslation
  articles/data-factory/connector-amazon-simple-storage-service.md
Labels: Accepted, In Progress

#346 Fix mistranslation
  articles/data-factory/connector-azure-cosmos-db.md
Labels: Accepted, In Progress

#349 Fix mistranslation
  articles/data-factory/connector-azure-data-lake-store.md
Labels: In Progress

#347 Fix mistranslation
  articles/data-factory/connector-azure-data-explorer.md
Labels: Accepted, In Progress

#351 Fix mistranslation
  articles/data-factory/connector-azure-file-storage.md
Labels: Accepted, In Progress

#352 Fix mistranslation
  articles/data-factory/connector-cassandra.md
Labels: Accepted, In Progress

#353 Fix mistranslation
  articles/data-factory/connector-db2.md
Labels: Accepted, In Progress

#354 Fix mistranslation
  articles/data-factory/connector-dynamics-ax.md
Labels: Accepted, In Progress

#356 Fix mistranslation
  articles/data-factory/connector-file-system.md
Labels: Accepted, In Progress

#357 Fix mistranslation
  articles/data-factory/connector-ftp.md
Labels: Accepted, In Progress

#355 Fix mistranslation
  articles/data-factory/connector-dynamics-crm-office-365.md
Labels: Accepted, In Progress

#358 Fix mistranslation
  articles/data-factory/connector-google-bigquery.md
Labels: Accepted, In Progress

#362 Fix mistranslation
  articles/data-factory/connector-impala.md
Labels: Accepted, In Progress

#363 Fix mistranslation
  articles/data-factory/connector-mongodb-legacy.md
Labels: Accepted, In Progress

#364 Fix mistranslation
  articles/data-factory/connector-netezza.md
Labels: Accepted, In Progress

#365 Fix mistranslation
  articles/data-factory/connector-odata.md
Labels: Accepted, In Progress

#366 Fix mistranslation
  articles/data-factory/connector-odbc.md
Labels: Accepted, In Progress

#367 Fix mistranslation
  articles/data-factory/connector-oracle.md
Labels: Accepted, In Progress

#369 Fix mistranslation
  articles/data-factory/connector-rest.md
Labels: Accepted, In Progress

#370 Fix mistranslation
  articles/data-factory/connector-salesforce.md
Labels: Accepted, In Progress

#372 Fix mistranslation
  articles/data-factory/connector-sap-business-warehouse-open-hub.md
Labels: Accepted, In Progress

#373 Fix mistranslation
  articles/data-factory/connector-sap-business-warehouse.md
Labels: Accepted, In Progress

#374 Fix mistranslation
  articles/data-factory/connector-sap-cloud-for-customer.md
Labels: Accepted, In Progress

#375 Fix mistranslation
  articles/data-factory/connector-sap-ecc.md
Labels: Accepted, In Progress

#376 Fix mistranslation
  articles/data-factory/connector-sap-hana.md
Labels: Accepted, In Progress

#371 Fix typo
  articles/virtual-machines/windows/storage-performance.md
Labels: Accepted, Linguistic Suggestion

#361 Update devtest-lab-guidance-prescriptive-adoption.md
  articles/lab-services/devtest-lab-guidance-prescriptive-adoption.md
Labels: Linguistic Suggestion, Partially Accepted

#378 Fix mistranslation
  articles/data-factory/connector-sql-server.md
Labels: Accepted, In Progress

#379 Fix mistranslation
  articles/data-factory/connector-sybase.md
Labels: Accepted, In Progress

#368 French update of "Concept-password-ban-bad..."
  articles/active-directory/authentication/concept-password-ban-bad-on-premises.md
Labels: In Progress, Linguistic Suggestion

#382 Fix mistranslation
  articles/data-factory/copy-activity-overview.md
Labels: Accepted, Linguistic Suggestion

#381 Fix mistranslation
  articles/data-factory/connector-teradata.md
Labels: Accepted, Linguistic Suggestion

#383 Fix mistranslation
  articles/data-factory/copy-activity-schema-and-type-mapping.md
Labels: Accepted, Linguistic Suggestion

#384 Fix mistranslation
  articles/data-factory/how-to-create-tumbling-window-trigger.md
Labels: Accepted, Linguistic Suggestion

#385 Fix mistranslation
  articles/data-factory/monitor-using-azure-monitor.md
Labels: Accepted, Linguistic Suggestion

#386 Fix mistranslation
  articles/data-factory/store-credentials-in-key-vault.md
Labels: Accepted, Linguistic Suggestion

#387 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-documentdb-connector.md
Labels: Accepted, Linguistic Suggestion

#388 Fix mistranslation
  articles/data-factory/v1/data-factory-build-your-first-pipeline-using-editor.md
Labels: Accepted, Linguistic Suggestion

#389 Fix mistranslation
  articles/data-factory/v1/data-factory-build-your-first-pipeline-using-powershell.md
Labels: Accepted, Linguistic Suggestion

#390 Fix mistranslation
  articles/data-factory/v1/data-factory-build-your-first-pipeline-using-rest-api.md
Labels: Accepted, In Progress

#391 Fix mistranslation
  articles/data-factory/v1/data-factory-copy-activity-tutorial-using-azure-portal.md
Labels: Accepted, In Progress

#392 Fix mistranslation
  articles/data-factory/v1/data-factory-copy-activity-tutorial-using-powershell.md
Labels: Accepted, In Progress

#393 Fix mistranslation
  articles/data-factory/v1/data-factory-copy-activity-tutorial-using-rest-api.md
Labels: Accepted, In Progress

#394 Fix mistranslation
  articles/data-factory/v1/data-factory-copy-activity-tutorial-using-visual-studio.md
Labels: Accepted, In Progress

#395 Fix mistranslation
  articles/data-factory/v1/data-factory-create-datasets.md
Labels: Accepted, In Progress

#399 Fix mistranslation
  articles/data-factory/v1/data-factory-hdfs-connector.md
Labels: Accepted, Linguistic Suggestion

#400 Fix mistranslation
  articles/data-factory/v1/data-factory-hive-activity.md
Labels: Accepted, Linguistic Suggestion

#397 Fix mistranslation
  articles/data-factory/v1/data-factory-create-pipelines.md
Labels: Accepted, Linguistic Suggestion

#401 Fix mistranslation
  articles/data-factory/v1/data-factory-http-connector.md
Labels: Accepted, Linguistic Suggestion

#398 Fix mistranslation
  articles/data-factory/v1/data-factory-ftp-connector.md
Labels: Accepted, Linguistic Suggestion

#402 Fix mistranslation
  articles/data-factory/v1/data-factory-json-scripting-reference.md
Labels: Accepted, Linguistic Suggestion

#405 Fix mistranslation
  articles/data-factory/v1/data-factory-map-reduce.md
Labels: Accepted, Linguistic Suggestion

#406 Fix mistranslation
  articles/data-factory/v1/data-factory-odata-connector.md
Labels: Accepted, Linguistic Suggestion

#408 Fix mistranslation
  articles/data-factory/v1/data-factory-on-premises-mongodb-connector.md
Labels: Accepted, In Progress

#409 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-file-system-connector.md
Labels: Accepted, In Progress

#410 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-mysql-connector.md
Labels: Accepted, In Progress
